# Generated by Django 5.1.1 on 2024-10-08 13:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('CC', 'Conta Corrente'), ('CP', 'Conta Poupança')], max_length=2)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('tipo', models.CharField(max_length=10)),
                ('categoria', models.CharField(choices=[('AL', 'Alimentação'), ('TR', 'Transporte'), ('SA', 'Saúde'), ('LA', 'Lazer'), ('SU', 'Supermercado')], max_length=2)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controle.conta')),
            ],
        ),
    ]
