# Generated by Django 5.1.1 on 2024-11-08 00:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0002_categoria_remove_transacao_tipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='controle.categoria'),
        ),
    ]
